services:
  backend:
    image: crpi-qeypgng4u8e2ezh6.cn-shanghai.personal.cr.aliyuncs.com/nan-fe/agents:backend
    container_name: agents-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: crpi-qeypgng4u8e2ezh6.cn-shanghai.personal.cr.aliyuncs.com/nan-fe/agents:frontend
    container_name: agents-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge