services:
  backend:
    image: ghcr.io/nan-fe/xhs-multi-agent-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      # - SILICONFLOW_MODEL=${SILICONFLOW_MODEL}
      # - COPYWRITE_MODEL=${COPYWRITE_MODEL}
      # - EMBEDING_MODEL=${EMBEDING_MODEL}
      # - GENARATION_MODEL=${GENARATION_MODEL}
      # - PLAN_MODEL=${PLAN_MODEL}
      # - INTENT_MODEL=${INTENT_MODEL}
      # - RANKER_MODEL=${RANKER_MODEL}
      # - IMAGE_MODEL=${IMAGE_MODEL}
      # - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      # - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      # - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      # - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      # - SILICONFLOW_BASE_URL=${SILICONFLOW_BASE_URL}
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    image: ghcr.io/nan-fe/xhs-multi-agent-frontend:latest
    build:
      context: ./frontend-ts
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge