/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 存活探针：进程已启动即可。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description 就绪探针：RAG 向量索引已就绪后再接流量（Kubernetes readiness）。
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display-labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Display Labels
         * @description 意图与 Agent 展示名映射，供前端静态拉取或调试。
         */
        get: operations["get_display_labels_api_display_labels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description 进入页面时拉取项目列表，按用户最近打开时间降序，默认定位第一个。
         */
        get: operations["list_projects_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description 新建对话时分配 project_id；无 topic/final_version 时不写入 projects 表。
         */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Conversation
         * @description 加载指定 project 的对话（从 versions 重建）。
         */
        get: operations["get_project_conversation_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description 删除历史对话（project 行及全部 versions）。
         */
        delete: operations["delete_project_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize Project
         * @description 页面关闭或新建话题时，将 versions 汇总写入 projects 表。
         */
        post: operations["finalize_project_projects_finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialog/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generatedialog
         * @description 对话式生成小红书内容
         */
        post: operations["generateDialog_dialog_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product_info/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Product Info
         * @description 获取选品池商品列表。
         */
        get: operations["list_product_info_product_info_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product_info/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Product Info
         * @description 识别商品链接信息，返回预览供用户确认（不入库）。
         */
        post: operations["preview_product_info_product_info_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product_info/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Product Info
         * @description 确认将已识别的商品加入选品池与 RAG 索引。
         */
        post: operations["confirm_product_info_product_info_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product_info/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product Info
         * @description 获取选品池商品详情（含头图与评论）。
         */
        get: operations["get_product_info_product_info__product_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Product Info
         * @description 从选品池删除商品。
         */
        delete: operations["delete_product_info_product_info__product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Share
         * @description 保存生成结果快照，用于公开分享页读取。
         */
        post: operations["create_share_shares_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Share
         * @description 读取公开分享快照。
         */
        get: operations["get_share_shares__share_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lark/oauth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lark Oauth Register
         * @description 动态客户端注册（DCR）：登记 redirect_uri 后用于 OAuth 授权回流。
         */
        post: operations["lark_oauth_register_lark_oauth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lark/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lark Oauth Authorize
         * @description 跳转飞书授权页（浏览器 302）。授权完成后回到 return_url。
         */
        get: operations["lark_oauth_authorize_lark_oauth_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lark/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lark Oauth Callback
         * @description 飞书 OAuth 回调：用 code 换 user_access_token 并跳回业务页。
         */
        get: operations["lark_oauth_callback_lark_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lark/oauth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lark Oauth User Status
         * @description 查询用户是否已完成飞书 OAuth 授权。
         */
        get: operations["lark_oauth_user_status_lark_oauth_user_get"];
        put?: never;
        post?: never;
        /**
         * Lark Oauth Disconnect
         * @description 解除用户飞书 OAuth 绑定。
         */
        delete: operations["lark_oauth_disconnect_lark_oauth_user_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lark/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lark Status
         * @description 飞书 bot 鉴权状态与通知群是否已配置。
         */
        get: operations["lark_status_lark_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lark/push-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lark Push Review
         * @description 将审核通过内容推送到飞书通知群（须服务端已配置 LARK_*）。
         */
        post: operations["lark_push_review_lark_push_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Social Status
         * @description 微博发布与 X 同步配置状态。
         */
        get: operations["social_status_social_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/weibo/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social Weibo Oauth Start
         * @description 在 Playwright Profile 内启动微博 OAuth 授权。
         */
        post: operations["social_weibo_oauth_start_social_weibo_oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/weibo/oauth/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Weibo Oauth Session Status */
        get: operations["social_weibo_oauth_session_status_social_weibo_oauth_session__session_id__get"];
        put?: never;
        post?: never;
        /** Social Weibo Oauth Session Close */
        delete: operations["social_weibo_oauth_session_close_social_weibo_oauth_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/weibo/oauth/session/{session_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Social Weibo Oauth Session Confirm */
        post: operations["social_weibo_oauth_session_confirm_social_weibo_oauth_session__session_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/weibo/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Social Weibo Oauth Callback
         * @description 微博 OAuth 浏览器回调页（token 交换由 Playwright 会话内监听完成）。
         */
        get: operations["social_weibo_oauth_callback_social_weibo_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/weibo/oauth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Weibo Oauth User Status */
        get: operations["social_weibo_oauth_user_status_social_weibo_oauth_user_get"];
        put?: never;
        post?: never;
        /** Social Weibo Oauth Disconnect */
        delete: operations["social_weibo_oauth_disconnect_social_weibo_oauth_user_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/weibo/login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social Weibo Login Start
         * @description Fallback：手动 Profile 登录微博（OAuth 未配置时使用）。
         */
        post: operations["social_weibo_login_start_social_weibo_login_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/weibo/login/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Social Weibo Login Close
         * @description 结束可视化登录会话。
         */
        delete: operations["social_weibo_login_close_social_weibo_login__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/weibo/login/{session_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social Weibo Login Confirm
         * @description 用户确认已在浏览器完成登录：检测并持久化 Profile。
         */
        post: operations["social_weibo_login_confirm_social_weibo_login__session_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/publish/weibo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social Publish Weibo
         * @description 异步发布到微博，返回 job_id 供轮询。
         */
        post: operations["social_publish_weibo_social_publish_weibo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/x/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social X Oauth Start
         * @description 在 Playwright Profile 内启动 X OAuth 授权。
         */
        post: operations["social_x_oauth_start_social_x_oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/x/oauth/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social X Oauth Session Status */
        get: operations["social_x_oauth_session_status_social_x_oauth_session__session_id__get"];
        put?: never;
        post?: never;
        /** Social X Oauth Session Close */
        delete: operations["social_x_oauth_session_close_social_x_oauth_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/x/oauth/session/{session_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Social X Oauth Session Confirm */
        post: operations["social_x_oauth_session_confirm_social_x_oauth_session__session_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/x/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Social X Oauth Callback
         * @description X OAuth 浏览器回调页（token 交换由 Playwright 会话内监听完成）。
         */
        get: operations["social_x_oauth_callback_social_x_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/x/oauth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social X Oauth User Status */
        get: operations["social_x_oauth_user_status_social_x_oauth_user_get"];
        put?: never;
        post?: never;
        /** Social X Oauth Disconnect */
        delete: operations["social_x_oauth_disconnect_social_x_oauth_user_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/x/login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social X Login Start
         * @description Fallback：手动 Profile 登录 X（OAuth 未配置时使用）。
         */
        post: operations["social_x_login_start_social_x_login_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/x/login/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Social X Login Close
         * @description 结束 X 可视化登录会话。
         */
        delete: operations["social_x_login_close_social_x_login__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/x/login/{session_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social X Login Confirm
         * @description 用户确认已在浏览器完成 X 登录：检测并持久化 Profile。
         */
        post: operations["social_x_login_confirm_social_x_login__session_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/publish/x": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social Publish X
         * @description 异步发布到 X，返回 job_id 供轮询。
         */
        post: operations["social_publish_x_social_publish_x_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/publish/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Social Publish Job Status
         * @description 查询社交媒体发布任务状态（微博 / X）。
         */
        get: operations["social_publish_job_status_social_publish__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/sync/x": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social Sync X Once
         * @description 手动触发一次 X → 微博同步（调试/运维）。
         */
        post: operations["social_sync_x_once_social_sync_x_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social-hotspots/analyze/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social Hotspots Analyze Stream
         * @description SSE 流式热点分析：阶段性返回检索与大模型整合结果。
         */
        post: operations["social_hotspots_analyze_stream_social_hotspots_analyze_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description 根路径
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HotspotAnalyzeRequest
         * @description 社交媒体热点分析请求。
         */
        HotspotAnalyzeRequest: {
            /**
             * Keyword
             * @default 商品宣传 营销 推广 种草 带货 品牌 新品 爆款
             */
            keyword: string;
            /** Platforms */
            platforms?: ("weibo" | "xhs" | "douyin" | "x" | "reddit")[];
            /**
             * Max Items Per Platform
             * @default 5
             */
            max_items_per_platform: number;
            /**
             * Locale
             * @default zh-CN
             */
            locale: string;
        };
        /**
         * LarkOAuthRegisterRequest
         * @description 动态客户端注册（DCR）。
         */
        LarkOAuthRegisterRequest: {
            /** Client Name */
            client_name: string;
            /** Redirect Uris */
            redirect_uris: string[];
            /** Scope */
            scope?: string | null;
        };
        /** LarkOAuthRegisterResponse */
        LarkOAuthRegisterResponse: {
            /** Client Id */
            client_id: string;
            /** Client Secret */
            client_secret: string;
            /** Client Id Issued At */
            client_id_issued_at: number;
            /**
             * Client Secret Expires At
             * @default 0
             */
            client_secret_expires_at: number;
            /** Redirect Uris */
            redirect_uris: string[];
            /** Scope */
            scope: string;
            /**
             * Grant Types
             * @default [
             *       "authorization_code"
             *     ]
             */
            grant_types: string[];
            /**
             * Response Types
             * @default [
             *       "code"
             *     ]
             */
            response_types: string[];
            /**
             * Token Endpoint Auth Method
             * @default none
             */
            token_endpoint_auth_method: string;
        };
        /**
         * LarkPushReviewRequest
         * @description 显式推送审核通过通知到飞书。
         */
        LarkPushReviewRequest: {
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Version */
            version?: string | null;
            /** Version Id */
            version_id?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Review Feedback */
            review_feedback?: string | null;
            /** Hashtags */
            hashtags?: string[] | null;
            /** User Id */
            user_id?: string | null;
        };
        /**
         * LarkStatusResponse
         * @description 飞书鉴权与通知配置状态。
         */
        LarkStatusResponse: {
            /** Auth */
            auth: {
                [key: string]: unknown;
            };
            /** Notify Chat Configured */
            notify_chat_configured: boolean;
            /** Notify Enabled */
            notify_enabled: boolean;
            /** Notify Mode */
            notify_mode: string;
            /** User Oauth */
            user_oauth?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ProductComment
         * @description 商品评论摘要（预览展示用）
         */
        ProductComment: {
            /** Content */
            content: string;
            /**
             * Nickname
             * @default
             */
            nickname: string;
            /**
             * Score
             * @default
             */
            score: string;
            /**
             * Creation Time
             * @default
             */
            creation_time: string;
        };
        /**
         * ProductInfoConfirmRequest
         * @description 确认将已识别的商品加入选品池
         */
        ProductInfoConfirmRequest: {
            /**
             * Preview Token
             * @description 预览接口返回的临时令牌
             */
            preview_token: string;
        };
        /**
         * ProductInfoCreateResponse
         * @description 创建商品后的响应
         */
        ProductInfoCreateResponse: {
            product: components["schemas"]["ProductItem"];
            /**
             * Message
             * @default 商品已加入选品池并同步至检索索引
             */
            message: string;
        };
        /**
         * ProductInfoPreviewRequest
         * @description 识别商品链接中的信息（不入库）
         */
        ProductInfoPreviewRequest: {
            /**
             * Url
             * @description 淘宝/天猫/京东商品详情页链接
             */
            url: string;
        };
        /**
         * ProductInfoPreviewResponse
         * @description 商品链接识别预览（待用户确认）
         */
        ProductInfoPreviewResponse: {
            /** Preview Token */
            preview_token: string;
            product: components["schemas"]["ProductItem"];
            /**
             * Message
             * @default 商品信息识别完成，请确认是否加入选品池
             */
            message: string;
        };
        /**
         * ProductItem
         * @description 选品池商品条目
         */
        ProductItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Price */
            price: number;
            /** Description */
            description: string;
            /** Sales */
            sales: number;
            /** Shop Name */
            shop_name: string;
            /** Url */
            url?: string | null;
            /** Cover Image */
            cover_image?: string | null;
            /** Comments */
            comments?: components["schemas"]["ProductComment"][];
        };
        /**
         * ProductListResponse
         * @description 选品池商品列表
         */
        ProductListResponse: {
            /** Items */
            items: components["schemas"]["ProductItem"][];
            /** Total */
            total: number;
        };
        /** ProjectConversationResponse */
        ProjectConversationResponse: {
            /** Project Id */
            project_id: string;
            /** Topic */
            topic?: string | null;
            /** Final Version */
            final_version?: string | null;
            /** Project Summary */
            project_summary?: string | null;
            /** Versions */
            versions?: components["schemas"]["VersionSnapshot"][];
        };
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            /** User Id */
            user_id?: string | null;
        };
        /** ProjectCreateResponse */
        ProjectCreateResponse: {
            /** Project Id */
            project_id: string;
        };
        /**
         * ProjectFinalizeRequest
         * @description 页面关闭或新建话题时，将 versions 汇总写入 projects。
         */
        ProjectFinalizeRequest: {
            /** Project Id */
            project_id: string;
            /** Session Id */
            session_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** ProjectFinalizeResponse */
        ProjectFinalizeResponse: {
            /** Project Id */
            project_id: string;
            /** Finalized */
            finalized: boolean;
            /** Final Version */
            final_version?: string | null;
            /**
             * Version Count
             * @default 0
             */
            version_count: number;
            /** Message */
            message?: string | null;
        };
        /** ProjectListItem */
        ProjectListItem: {
            /** Project Id */
            project_id: string;
            /**
             * Topic
             * @default
             */
            topic: string;
            /** Final Version */
            final_version?: string | null;
            /**
             * Project Summary
             * @default
             */
            project_summary: string;
            /**
             * Version Count
             * @default 0
             */
            version_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Last Accessed At
             * Format: date-time
             */
            last_accessed_at: string;
            /**
             * Finalized
             * @default false
             */
            finalized: boolean;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Projects */
            projects?: components["schemas"]["ProjectListItem"][];
        };
        /** PublishJobResponse */
        PublishJobResponse: {
            /** Job Id */
            job_id: string;
            /** Platform */
            platform: string;
            /** Status */
            status: string;
            /** Progress */
            progress?: string[];
            /** Post Url */
            post_url?: string | null;
            /** Error */
            error?: string | null;
            /** Screenshot Path */
            screenshot_path?: string | null;
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
            /** Payload Summary */
            payload_summary?: {
                [key: string]: unknown;
            };
        };
        /**
         * ShareCreateRequest
         * @description 创建公开分享快照的请求
         */
        ShareCreateRequest: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Hashtags */
            hashtags?: string[];
            /** Image Url */
            image_url?: string | null;
            /** Message */
            message?: string | null;
        };
        /**
         * ShareCreateResponse
         * @description 创建分享后的响应
         */
        ShareCreateResponse: {
            /** Share Id */
            share_id: string;
            share: components["schemas"]["ShareSnapshot"];
        };
        /**
         * ShareSnapshot
         * @description 公开分享快照
         */
        ShareSnapshot: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Hashtags */
            hashtags?: string[];
            /** Image Url */
            image_url?: string | null;
            /** Message */
            message?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /** SocialStatusResponse */
        SocialStatusResponse: {
            /** Weibo Publish Enabled */
            weibo_publish_enabled: boolean;
            /** Weibo */
            weibo: {
                [key: string]: unknown;
            };
            /**
             * Weibo Oauth Configured
             * @default false
             */
            weibo_oauth_configured: boolean;
            /**
             * X Publish Enabled
             * @default false
             */
            x_publish_enabled: boolean;
            /** X */
            x?: {
                [key: string]: unknown;
            };
            /**
             * X Oauth Configured
             * @default false
             */
            x_oauth_configured: boolean;
            /** X Sync Enabled */
            x_sync_enabled: boolean;
            /** X Sync Username */
            x_sync_username?: string | null;
            /** X Sync Interval Seconds */
            x_sync_interval_seconds: number;
            /** Review Required */
            review_required: boolean;
            /**
             * X Review Required
             * @default true
             */
            x_review_required: boolean;
            /**
             * Auto On Complete
             * @default true
             */
            auto_on_complete: boolean;
            /**
             * Publish Engine
             * @default playwright
             */
            publish_engine: string;
            /**
             * X Publish Engine
             * @default playwright
             */
            x_publish_engine: string;
            /** Dry Run */
            dry_run: boolean;
            /**
             * X Dry Run
             * @default false
             */
            x_dry_run: boolean;
        };
        /**
         * UserInput
         * @description 用户输入模型
         */
        UserInput: {
            /** Prompt */
            prompt: string;
            /** Session Id */
            session_id: string;
            /** Last Event Id */
            last_event_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionSnapshot */
        VersionSnapshot: {
            /** Version Id */
            version_id: string;
            /** Version Label */
            version_label: string;
            /** Version Number */
            version_number: number;
            /** Parent Version Id */
            parent_version_id?: string | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** User Input */
            user_input?: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Intent */
            intent?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WeiboLoginStartResponse */
        WeiboLoginStartResponse: {
            /** Session Id */
            session_id: string;
            /** Logged In */
            logged_in: boolean;
            /** Current Url */
            current_url: string;
            /** Profile Path */
            profile_path: string;
            /**
             * Viewport Width
             * @default 1280
             */
            viewport_width: number;
            /**
             * Viewport Height
             * @default 900
             */
            viewport_height: number;
        };
        /** WeiboLoginStatusResponse */
        WeiboLoginStatusResponse: {
            /** Session Id */
            session_id: string;
            /** Logged In */
            logged_in: boolean;
            /** Current Url */
            current_url: string;
            /** Profile Path */
            profile_path: string;
        };
        /** WeiboOAuthSessionResponse */
        WeiboOAuthSessionResponse: {
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: string;
            /** Logged In */
            logged_in: boolean;
            /**
             * Oauth Completed
             * @default false
             */
            oauth_completed: boolean;
            /** Oauth Error */
            oauth_error?: string | null;
            /** Weibo Screen Name */
            weibo_screen_name?: string | null;
            /** Current Url */
            current_url: string;
            /** Profile Path */
            profile_path: string;
            /**
             * Viewport Width
             * @default 1280
             */
            viewport_width: number;
            /**
             * Viewport Height
             * @default 900
             */
            viewport_height: number;
        };
        /** WeiboOAuthStartRequest */
        WeiboOAuthStartRequest: {
            /** User Id */
            user_id: string;
        };
        /** WeiboPublishCreateResponse */
        WeiboPublishCreateResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
        };
        /**
         * WeiboPublishRequest
         * @description 触发微博自动发布。
         */
        WeiboPublishRequest: {
            /**
             * User Id
             * @default
             */
            user_id: string;
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Hashtags */
            hashtags?: string[] | null;
            /** Image Url */
            image_url?: string | null;
            /** Share Url */
            share_url?: string | null;
            /** Review Approved */
            review_approved?: boolean | null;
            /** Version Id */
            version_id?: string | null;
        };
        /** XOAuthSessionResponse */
        XOAuthSessionResponse: {
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: string;
            /** Logged In */
            logged_in: boolean;
            /**
             * Oauth Completed
             * @default false
             */
            oauth_completed: boolean;
            /** Oauth Error */
            oauth_error?: string | null;
            /** X Username */
            x_username?: string | null;
            /** Current Url */
            current_url: string;
            /** Profile Path */
            profile_path: string;
            /**
             * Viewport Width
             * @default 1280
             */
            viewport_width: number;
            /**
             * Viewport Height
             * @default 900
             */
            viewport_height: number;
        };
        /** XOAuthStartRequest */
        XOAuthStartRequest: {
            /** User Id */
            user_id: string;
        };
        /** XPublishCreateResponse */
        XPublishCreateResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
        };
        /**
         * XPublishRequest
         * @description 触发 X 自动发布（Playwright Profile）。
         */
        XPublishRequest: {
            /**
             * User Id
             * @default
             */
            user_id: string;
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Hashtags */
            hashtags?: string[] | null;
            /** Image Url */
            image_url?: string | null;
            /** Share Url */
            share_url?: string | null;
            /** Review Approved */
            review_approved?: boolean | null;
            /** Version Id */
            version_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_display_labels_api_display_labels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_conversation_projects__project_id__get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_id__delete: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_project_projects_finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectFinalizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFinalizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generateDialog_dialog_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_info_product_info_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    preview_product_info_product_info_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInfoPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductInfoPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_product_info_product_info_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInfoConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductInfoCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_info_product_info__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_info_product_info__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_shares_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_shares__share_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lark_oauth_register_lark_oauth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LarkOAuthRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LarkOAuthRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lark_oauth_authorize_lark_oauth_authorize_get: {
        parameters: {
            query: {
                user_id: string;
                return_url: string;
                client_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lark_oauth_callback_lark_oauth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lark_oauth_user_status_lark_oauth_user_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lark_oauth_disconnect_lark_oauth_user_delete: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lark_status_lark_status_get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LarkStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lark_push_review_lark_push_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LarkPushReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_status_social_status_get: {
        parameters: {
            query?: {
                user_id?: string;
                force_refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_oauth_start_social_weibo_oauth_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeiboOAuthStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboOAuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_oauth_session_status_social_weibo_oauth_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboOAuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_oauth_session_close_social_weibo_oauth_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_oauth_session_confirm_social_weibo_oauth_session__session_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboLoginStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_oauth_callback_social_weibo_oauth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_oauth_user_status_social_weibo_oauth_user_get: {
        parameters: {
            query: {
                user_id: string;
                force_refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_oauth_disconnect_social_weibo_oauth_user_delete: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_login_start_social_weibo_login_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeiboOAuthStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboLoginStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_login_close_social_weibo_login__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_weibo_login_confirm_social_weibo_login__session_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboLoginStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_publish_weibo_social_publish_weibo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeiboPublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboPublishCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_oauth_start_social_x_oauth_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["XOAuthStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XOAuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_oauth_session_status_social_x_oauth_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XOAuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_oauth_session_close_social_x_oauth_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_oauth_session_confirm_social_x_oauth_session__session_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboLoginStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_oauth_callback_social_x_oauth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_oauth_user_status_social_x_oauth_user_get: {
        parameters: {
            query: {
                user_id: string;
                force_refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_oauth_disconnect_social_x_oauth_user_delete: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_login_start_social_x_login_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["XOAuthStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboLoginStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_login_close_social_x_login__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_x_login_confirm_social_x_login__session_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeiboLoginStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_publish_x_social_publish_x_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["XPublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XPublishCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_publish_job_status_social_publish__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_sync_x_once_social_sync_x_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    social_hotspots_analyze_stream_social_hotspots_analyze_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotspotAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
