/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 存活探针：进程已启动即可。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description 就绪探针：RAG 向量索引已就绪后再接流量（Kubernetes readiness）。
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialog/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generatedialog
         * @description 对话式生成小红书内容
         */
        post: operations["generateDialog_dialog_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description 根路径
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * UserInput
         * @description 用户输入模型
         */
        UserInput: {
            /** Prompt */
            prompt: string;
            /** Session Id */
            session_id: string;
            /** Last Event Id */
            last_event_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** ProjectFinalizeRequest */
        ProjectFinalizeRequest: {
            project_id: string;
            session_id?: string | null;
            user_id?: string | null;
        };
        /** ProjectFinalizeResponse */
        ProjectFinalizeResponse: {
            project_id: string;
            finalized: boolean;
            final_version?: string | null;
            version_count: number;
            message?: string | null;
        };
        /** ProjectCreateResponse */
        ProjectCreateResponse: {
            project_id: string;
        };
        /** VersionSnapshot */
        VersionSnapshot: {
            version_id: string;
            version_label: string;
            version_number: number;
            parent_version_id?: string | null;
            summary?: string;
            user_input?: string | null;
            result: Record<string, unknown>;
            intent?: string | null;
            created_at: string;
        };
        /** ProjectConversationResponse */
        ProjectConversationResponse: {
            project_id: string;
            topic?: string | null;
            final_version?: string | null;
            project_summary?: string | null;
            versions: components["schemas"]["VersionSnapshot"][];
        };
        /** ProjectListItem */
        ProjectListItem: {
            project_id: string;
            topic?: string;
            final_version?: string | null;
            project_summary?: string;
            version_count: number;
            updated_at: string;
            last_accessed_at: string;
            finalized?: boolean;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            projects: components["schemas"]["ProjectListItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generateDialog_dialog_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
